name: gemini_getx
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  # network
  http: ^0.13.3
  http_interceptor: ^1.0.2
  dartz: ^0.10.1
  logger: ^1.1.0

  # file
  image_picker: ^1.1.1
  video_player: ^2.8.6
  lottie: ^3.0.0

  # speech
  speech_to_text: ^6.6.1
  flutter_tts: ^4.0.2

  # getX
  get: ^4.6.6
  hive: ^2.2.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  path_provider: ^2.1.3
  shake: ^2.2.0
  linkify: ^5.0.0
  flutter_linkify: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true


  assets:
     - assets/images/
     - assets/videos/
     - assets/animations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
